// Builds lib/widgets/monthly_climb/climb_trail_table.dart from the trail
// that Scene Art Batch 0 extracted from Green Slope's image
// (docs/design/scene-art/batch0/trail_green.json, written by
// tool/scene_art/extract_trail.py). Used by generate_climb_trail_test.dart
// to write the file and by test/climb_trail_table_test.dart to check the
// committed file is current: design decision D3, now fed by the image
// (scene art S2) instead of a curve.

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

const climbTrailTablePath = 'lib/widgets/monthly_climb/climb_trail_table.dart';
const climbTrailSourcePath = 'docs/design/scene-art/batch0/trail_green.json';

/// Fixed-point text: stable across runs and platforms.
String _f(double v, int digits) => v.toStringAsFixed(digits);

String generateClimbTrailTable({String source = climbTrailSourcePath}) {
  final json =
      jsonDecode(File(source).readAsStringSync()) as Map<String, dynamic>;
  final size = (json['image_size_px'] as List).cast<num>();
  final width = size[0].toDouble(), height = size[1].toDouble();
  final polyline = [
    for (final p in json['polyline'] as List)
      ((p as List)[0] as num).toDouble(),
  ];
  final ys = [
    for (final p in json['polyline'] as List)
      ((p as List)[1] as num).toDouble(),
  ];
  final chords = [
    for (final c in json['chord_px'] as List) (c as num).toDouble() / width
  ];
  final runs = [
    for (final r in json['run_px'] as List)
      [for (final v in r as List) (v as num).toDouble() / width]
  ];
  // Arc length in image-width units: x as is, y × height ÷ width.
  final aspect = width / height;
  final cumulative = <double>[0];
  for (var i = 1; i < polyline.length; i++) {
    final dx = polyline[i] - polyline[i - 1];
    final dy = (ys[i] - ys[i - 1]) / aspect;
    cumulative.add(cumulative.last + math.sqrt(dx * dx + dy * dy));
  }
  (double, double) at(double s) {
    var i = 1;
    while (i < cumulative.length - 1 && cumulative[i] < s) {
      i++;
    }
    final a = cumulative[i - 1], b = cumulative[i];
    final t = b == a ? 0.0 : ((s - a) / (b - a)).clamp(0.0, 1.0);
    return (
      polyline[i - 1] + (polyline[i] - polyline[i - 1]) * t,
      ys[i - 1] + (ys[i] - ys[i - 1]) * t
    );
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by scripts/generate_climb_trail.sh from')
    ..writeln('// $climbTrailSourcePath; do not edit.')
    ..writeln('// test/climb_trail_table_test.dart fails when this file and '
        'the trail disagree.')
    ..writeln()
    ..writeln('/// The image the trail was extracted from, width ÷ height '
        '(${width.toInt()} × ${height.toInt()} px).')
    ..writeln('const climbImageAspect = ${_f(aspect, 5)};')
    ..writeln()
    ..writeln("/// The trail's center line, foot to summit, normalized: x ÷ "
        'the image')
    ..writeln("/// width, y ÷ its height (scene art S2). Every theme's image "
        'keeps its')
    ..writeln('/// trail here (S4, checked by tool/scene_art/check_theme.py).')
    ..writeln('const climbTrail = <(double, double)>[');
  for (var i = 0; i < polyline.length; i++) {
    out.writeln('  (${_f(polyline[i], 5)}, ${_f(ys[i], 5)}),');
  }
  out
    ..writeln('];')
    ..writeln()
    ..writeln("/// The trail's horizontal width through each point of "
        '[climbTrail], ÷ the')
    ..writeln("/// image width: an upright avatar's footprint lies along x on "
        'any leg (G3).')
    ..writeln('const climbTrailChords = <double>[');
  for (final c in chords) {
    out.writeln('  ${_f(c, 5)},');
  }
  out
    ..writeln('];')
    ..writeln()
    ..writeln("/// The trail's horizontal run through each point of "
        '[climbTrail]: its left and')
    ..writeln("/// right edge, ÷ the image width (not centred on the centre "
        'line on a bend).')
    ..writeln('/// Save points must stay off it (Stage 2).')
    ..writeln('const climbTrailRuns = <(double, double)>[');
  for (final r in runs) {
    out.writeln('  (${_f(r[0], 5)}, ${_f(r[1], 5)}),');
  }
  out
    ..writeln('];')
    ..writeln()
    ..writeln('/// Where each day of a 28–31-day month stands, normalized like '
        '[climbTrail],')
    ..writeln('/// evenly spaced by arc length: entry d is day d, day 0 the '
        'foot, the last')
    ..writeln("/// entry the summit. Placing it on screen is the camera's job "
        '(D3).')
    ..writeln('const climbStepTable = <int, List<(double, double)>>{');
  for (var days = 28; days <= 31; days++) {
    out.writeln('  $days: [');
    for (var d = 0; d <= days; d++) {
      final (x, y) = at(cumulative.last * d / days);
      out.writeln('    (${_f(x, 5)}, ${_f(y, 5)}),');
    }
    out.writeln('  ],');
  }
  out.writeln('};');
  return out.toString();
}
