// Builds lib/widgets/monthly_climb/climb_table.dart from the frozen curve
// (ClimbRoute). Used by generate_climb_table_test.dart to write the file and
// by test/climb_table_test.dart to check the committed file is current.

import 'package:grammar_lens/widgets/monthly_climb/climb_route.dart';

const climbTablePath = 'lib/widgets/monthly_climb/climb_table.dart';

/// Fixed-point text for a normalized coordinate: stable across runs and
/// platforms, 1/100000 of the scene (0.003 units across, 0.007 down).
String _n(double v) => v.toStringAsFixed(5);

String generateClimbTable() {
  const size = ClimbRoute.sceneSize;
  final out = StringBuffer()
    ..writeln('// GENERATED by scripts/generate_climb_table.sh from '
        'ClimbRoute; do not edit.')
    ..writeln('// test/climb_table_test.dart fails when this file and the '
        'curve disagree.')
    ..writeln()
    ..writeln('/// Where each day of a 28–31-day month stands, normalized to '
        'mountain space:')
    ..writeln('/// x ÷ ${size.width.toInt()} and y ÷ ${size.height.toInt()} '
        'of `ClimbRoute.sceneSize`. Entry d is day d: day 0 is')
    ..writeln('/// the foot, the last entry is the summit. Placing it on '
        'screen is the')
    ..writeln("/// camera's job (design decision D3), not this table's.")
    ..writeln('const climbStepTable = <int, List<(double, double)>>{');
  for (var days = 28; days <= 31; days++) {
    final route = ClimbRoute(days);
    out.writeln('  $days: [');
    for (var d = 0; d <= days; d++) {
      final p = route.pointAt(d.toDouble());
      out.writeln('    (${_n(p.dx / size.width)}, ${_n(p.dy / size.height)}),');
    }
    out.writeln('  ],');
  }
  out.writeln('};');
  return out.toString();
}
