// Builds lib/widgets/monthly_climb/climb_save_point_table.dart from Scene
// Art Stage 2's placement (docs/design/scene-art/stage2/placement.json,
// tool/scene_art/place_save_points.py) and object data (objects.json,
// tool/scene_art/export_objects.py). Used by
// generate_climb_save_points_test.dart to write the file and by
// test/climb_save_point_table_test.dart to check it is current, the same
// pattern as the trail table (D3).

import 'dart:convert';
import 'dart:io';

const climbSavePointTablePath =
    'lib/widgets/monthly_climb/climb_save_point_table.dart';
const climbPlacementSourcePath = 'docs/design/scene-art/stage2/placement.json';
const climbObjectsSourcePath = 'docs/design/scene-art/stage2/objects.json';

String _f(num v, [int digits = 5]) => v.toDouble().toStringAsFixed(digits);

Map<String, dynamic> _read(String path) =>
    jsonDecode(File(path).readAsStringSync()) as Map<String, dynamic>;

String generateClimbSavePointTable() {
  final placement = _read(climbPlacementSourcePath);
  final objects = _read(climbObjectsSourcePath);
  final objectData = objects['objects'] as Map<String, dynamic>;
  final out = StringBuffer()
    ..writeln('// GENERATED by scripts/generate_climb_save_points.sh from')
    ..writeln('// $climbPlacementSourcePath and')
    ..writeln('// $climbObjectsSourcePath; do not edit.')
    ..writeln('// test/climb_save_point_table_test.dart fails when this file '
        'and its sources disagree.')
    ..writeln()
    ..writeln('/// The save points (scene art G4, G9): (clearing, object, the '
        "clearing's centre")
    ..writeln("/// x and y, the clearing's box width and height, the object's "
        'width as a')
    ..writeln("/// share of the clearing's), normalized to the image like "
        '`climbTrail`. The')
    ..writeln("/// object's base stands [climbSavePointBaseDrop] of the "
        "clearing's height")
    ..writeln('/// below its centre.')
    ..writeln('const climbSavePointTable = <(String, String, double, double, '
        'double, double, double)>[');
  for (final p in (placement['save_points'] as List).cast<Map>()) {
    final c = (p['center_norm'] as List).cast<num>();
    final b = (p['box_norm'] as List).cast<num>();
    out.writeln("  ('${p['clearing']}', '${p['object']}', ${_f(c[0])}, "
        '${_f(c[1])}, ${_f(b[0])}, ${_f(b[1])}, ${_f(p['ratio'] as num, 2)}),');
  }
  final drop = ((placement['save_points'] as List).first as Map)['base_drop'];
  final flag = placement['flag'] as Map;
  final fc = (flag['center_norm'] as List).cast<num>();
  final fb = (flag['box_norm'] as List).cast<num>();
  final gains = (objects['dark_gain'] as Map).cast<String, List>();
  out
    ..writeln('];')
    ..writeln()
    ..writeln('const climbSavePointBaseDrop = ${_f(drop as num, 2)};')
    ..writeln()
    ..writeln("/// The flag (the summit_flag asset): the month's goal, on its "
        'own clearing,')
    ..writeln('/// in the same fields as [climbSavePointTable]; it lights only '
        'on the')
    ..writeln("/// month's last step.")
    ..writeln("const climbFlag = ('${flag['clearing']}', '${flag['object']}', "
        '${_f(fc[0])}, ${_f(fc[1])}, ${_f(fb[0])}, ${_f(fb[1])}, '
        '${_f(flag['ratio'] as num, 2)});')
    ..writeln()
    ..writeln("/// Each object asset's height ÷ width (assets/climb/objects/).")
    ..writeln('const climbObjectAspects = <String, double>{');
  for (final e in objectData.entries) {
    out.writeln(
        "  '${e.key}': ${_f((e.value as Map)['aspect_h_over_w'] as num)},");
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln('/// Dark mode (G6): per-channel gain, dark ÷ light, of the '
        "clearings' ground")
    ..writeln("/// in the theme's two backgrounds, by theme id.")
    ..writeln(
        'const climbObjectDarkGain = <String, (double, double, double)>{');
  for (final e in gains.entries) {
    final g = e.value.cast<num>();
    out.writeln("  '${e.key}': (${_f(g[0], 4)}, ${_f(g[1], 4)}, "
        '${_f(g[2], 4)}),');
  }
  out.writeln('};');
  return out.toString();
}
