import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../theme.dart';
import 'brand_mark.dart';
import 'brand_wordmark.dart';

/// Geometry of the launch splash, shared with the iOS static launch screen.
///
/// The static screen (`ios/Runner/Base.lproj/LaunchScreen.storyboard` plus
/// `LaunchImage`, generated by `scripts/generate_launch_image.sh`) must be
/// identical to the splash's first frame, so both read these numbers: the
/// storyboard centers a [logoSize] image [logoCenterOffsetY] pt from the
/// screen's center, and the image is the logo drawn at [initialLogoScale].
/// `test/launch_image_test.dart` checks the storyboard and the images agree.
class LaunchSplashLayout {
  LaunchSplashLayout._();

  /// Size of the splash relative to its first version (logo 100 pt,
  /// wordmark 34 pt). The owner asked for 1.4 after the device check; 1.25
  /// is the largest that keeps 24 pt on each side of the wordmark at 320 pt
  /// wide (the wordmark is 216.7 pt wide at 1.0, so 270.9 pt at 1.25).
  static const double scale = 1.25;

  /// The logo's box, in logical points (BrandMark's 100-unit space, scaled).
  static const double logoSize = 100 * scale;

  /// The logo's scale on the first frame; it settles to 1.0.
  static const double initialLogoScale = 0.92;

  /// Space between the logo's box and the wordmark.
  static const double wordmarkGap = 16 * scale;

  /// The wordmark's font size and letter spacing.
  static const double wordmarkFontSize = 34 * scale;
  static const double wordmarkLetterSpacing = -0.5 * scale;

  /// The wordmark's height in NunitoSans at [wordmarkFontSize] (measured;
  /// `test/launch_gate_test.dart` checks it with the bundled font).
  static const double wordmarkHeight = 58;

  /// Vertical offset of the logo's center from the screen's center, chosen
  /// so the logo, the gap and the wordmark together (125 + 20 + 58 = 203 pt)
  /// are centered: 125 / 2 − 203 / 2 = −39. A literal because the
  /// storyboard's constraint needs the same number.
  static const double logoCenterOffsetY = -39;
}

/// Durations of the launch splash. The intro is at most [intro] plus
/// [exit]; Home is never shown before launch work has finished either.
class LaunchTiming {
  LaunchTiming._();

  /// Logo settle, wordmark fade and a short hold on the finished frame.
  static const Duration intro = Duration(milliseconds: 1000);

  /// The logo scales 0.92 → 1.0 over this share of [intro].
  static const Interval logoScale =
      Interval(0.0, 0.6, curve: Curves.easeOutCubic);

  /// The wordmark fades in over this share of [intro]; the rest is a hold,
  /// so the finished wordmark is readable before the splash fades.
  static const Interval wordmarkFade =
      Interval(0.3, 0.8, curve: Curves.easeOut);

  /// The splash fades out over the app.
  static const Duration exit = Duration(milliseconds: 200);
}

/// The app's root on a cold start: shows the launch splash while
/// [initialize] (Firebase, RevenueCat) runs, and the app once both the
/// splash's intro and that launch work have finished.
///
/// [initialize] is called once, when the gate is first built. The app is
/// built only after it completes, so nothing in it
/// can reach Firebase or RevenueCat before they are configured; it then
/// sits under the splash until the intro ends, and the splash fades out
/// over it. With Reduce Motion there is no intro and no fade.
///
/// This widget exists once per process, at the root, so the splash plays
/// only on a cold start: returning from the background does not rebuild it.
class LaunchGate extends StatefulWidget {
  const LaunchGate({
    super.key,
    required this.initialize,
    required this.app,
  });

  final Future<void> Function() initialize;
  final WidgetBuilder app;

  @override
  State<LaunchGate> createState() => _LaunchGateState();
}

class _LaunchGateState extends State<LaunchGate>
    with SingleTickerProviderStateMixin {
  late final AnimationController _exit;

  bool _ready = false;
  bool _introDone = false;
  bool _reduceMotion = false;
  bool _splashGone = false;

  @override
  void initState() {
    super.initState();
    _exit = AnimationController(vsync: this, duration: LaunchTiming.exit);
    // Launch work reports its own failures; the app starts either way.
    Future.sync(widget.initialize).catchError((Object _) {}).whenComplete(() {
      if (!mounted) return;
      setState(() => _ready = true);
      _maybeExit();
    });
  }

  @override
  void dispose() {
    _exit.dispose();
    super.dispose();
  }

  void _onIntroDone(bool reduceMotion) {
    if (!mounted) return;
    _introDone = true;
    _reduceMotion = reduceMotion;
    _maybeExit();
  }

  void _maybeExit() {
    if (!_ready || !_introDone || _splashGone) return;
    if (_reduceMotion) {
      setState(() => _splashGone = true);
      return;
    }
    if (_exit.isAnimating) return;
    _exit.forward().whenComplete(() {
      if (mounted) setState(() => _splashGone = true);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      textDirection: TextDirection.ltr,
      fit: StackFit.expand,
      children: [
        if (_ready)
          KeyedSubtree(
            key: const ValueKey('launch-app'),
            child: LaunchSplashScope(
              covering: !_splashGone,
              child: ExcludeSemantics(
                excluding: !_splashGone,
                child: Builder(builder: widget.app),
              ),
            ),
          ),
        if (!_splashGone)
          FadeTransition(
            key: const ValueKey('launch-splash'),
            opacity: ReverseAnimation(_exit),
            child: AbsorbPointer(
              child: MediaQuery.fromView(
                view: View.of(context),
                child: LaunchSplash(onIntroDone: _onIntroDone),
              ),
            ),
          ),
      ],
    );
  }
}

/// Tells the app whether the launch splash still covers it: true from the
/// moment the app is built under the splash until the splash's fade has
/// finished. Screens with an entrance animation (Welcome) hold it until
/// then, so it is not played unseen. Without a [LaunchGate] above (tests,
/// previews) nothing is covered.
class LaunchSplashScope extends InheritedWidget {
  const LaunchSplashScope({
    super.key,
    required this.covering,
    required super.child,
  });

  final bool covering;

  /// Whether the splash covers [context]'s screen; rebuilds it when that
  /// changes.
  static bool coveringOf(BuildContext context) =>
      context
          .dependOnInheritedWidgetOfExactType<LaunchSplashScope>()
          ?.covering ??
      false;

  @override
  bool updateShouldNotify(LaunchSplashScope oldWidget) =>
      covering != oldWidget.covering;
}

/// The splash itself: the logo settles from [LaunchSplashLayout.initialLogoScale]
/// to full size and the "GrammarLens" wordmark fades in.
///
/// Follows the system appearance, not the in-app theme preference: the
/// native launch screen before it can only follow the system, and the
/// in-app preference is not read yet. With Reduce Motion the logo stays at
/// its first-frame scale (no jump from the static screen) and the wordmark
/// is shown at once.
class LaunchSplash extends StatefulWidget {
  const LaunchSplash({super.key, this.onIntroDone});

  /// Called once, when the intro has finished (at once with Reduce Motion),
  /// with whether Reduce Motion was on.
  final void Function(bool reduceMotion)? onIntroDone;

  @override
  State<LaunchSplash> createState() => _LaunchSplashState();
}

class _LaunchSplashState extends State<LaunchSplash>
    with SingleTickerProviderStateMixin {
  late final AnimationController _intro;
  late final Animation<double> _logoScale = Tween<double>(
    begin: LaunchSplashLayout.initialLogoScale,
    end: 1,
  ).animate(CurvedAnimation(parent: _intro, curve: LaunchTiming.logoScale));
  late final Animation<double> _wordmarkOpacity =
      CurvedAnimation(parent: _intro, curve: LaunchTiming.wordmarkFade);

  bool _started = false;
  bool _reduceMotion = false;

  @override
  void initState() {
    super.initState();
    _intro = AnimationController(vsync: this, duration: LaunchTiming.intro);
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (_started) return;
    _started = true;
    _reduceMotion = MediaQuery.disableAnimationsOf(context);
    if (_reduceMotion) {
      WidgetsBinding.instance.addPostFrameCallback(
        (_) => widget.onIntroDone?.call(true),
      );
    } else {
      _intro.forward().whenComplete(() => widget.onIntroDone?.call(false));
    }
  }

  @override
  void dispose() {
    _intro.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final brightness = MediaQuery.platformBrightnessOf(context);
    final theme = buildAppTheme(brightness);
    final colorScheme = theme.colorScheme;

    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: brightness == Brightness.dark
          ? SystemUiOverlayStyle.light
          : SystemUiOverlayStyle.dark,
      child: Theme(
        data: theme,
        child: ColoredBox(
          color: colorScheme.surfaceContainerLow,
          child: LayoutBuilder(
            builder: (context, constraints) {
              final logoCenterY = constraints.maxHeight / 2 +
                  LaunchSplashLayout.logoCenterOffsetY;
              const half = LaunchSplashLayout.logoSize / 2;
              return Stack(
                textDirection: TextDirection.ltr,
                children: [
                  Positioned(
                    left: constraints.maxWidth / 2 - half,
                    top: logoCenterY - half,
                    width: LaunchSplashLayout.logoSize,
                    height: LaunchSplashLayout.logoSize,
                    child: ExcludeSemantics(
                      child: _reduceMotion
                          ? const LaunchLogo(
                              scale: LaunchSplashLayout.initialLogoScale)
                          : ScaleTransition(
                              scale: _logoScale,
                              child: const LaunchLogo(),
                            ),
                    ),
                  ),
                  Positioned(
                    left: 0,
                    right: 0,
                    top: logoCenterY + half + LaunchSplashLayout.wordmarkGap,
                    child: FadeTransition(
                      opacity: _reduceMotion
                          ? kAlwaysCompleteAnimation
                          : _wordmarkOpacity,
                      child: BrandWordmark(
                        textAlign: TextAlign.center,
                        textDirection: TextDirection.ltr,
                        maxLines: 1,
                        // A logotype, not body text: fixed like the logo.
                        textScaler: TextScaler.noScaling,
                        // Its own style, not a copy of a text theme style:
                        // the logotype's measured height
                        // ([LaunchSplashLayout.wordmarkHeight]) is the font's
                        // natural line height, and the 1.2.0 type scale
                        // sets explicit line heights on every style.
                        style: TextStyle(
                                fontFamily:
                                    theme.textTheme.headlineLarge?.fontFamily,
                                fontSize: LaunchSplashLayout.wordmarkFontSize,
                                letterSpacing:
                                    LaunchSplashLayout.wordmarkLetterSpacing,
                                color: colorScheme.onSurface)
                            .withWeight(FontWeight.w700),
                      ),
                    ),
                  ),
                ],
              );
            },
          ),
        ),
      ),
    );
  }
}

/// The logo in its [LaunchSplashLayout.logoSize] box, optionally scaled
/// about its center. Also what `scripts/generate_launch_image.sh` renders
/// for the static launch image, at [LaunchSplashLayout.initialLogoScale].
class LaunchLogo extends StatelessWidget {
  const LaunchLogo({super.key, this.scale = 1});

  final double scale;

  @override
  Widget build(BuildContext context) {
    const mark = BrandMark(size: LaunchSplashLayout.logoSize);
    return SizedBox.square(
      dimension: LaunchSplashLayout.logoSize,
      child: scale == 1 ? mark : Transform.scale(scale: scale, child: mark),
    );
  }
}
