// GENERATED by scripts/generate_climb_save_points.sh from
// docs/design/scene-art/stage2/placement.json and
// docs/design/scene-art/stage2/objects.json; do not edit.
// test/climb_save_point_table_test.dart fails when this file and its sources disagree.

/// The save points (scene art G4, G9): (clearing, object, the clearing's centre
/// x and y, the clearing's box width and height, the object's width as a
/// share of the clearing's), normalized to the image like `climbTrail`. The
/// object's base stands [climbSavePointBaseDrop] of the clearing's height
/// below its centre.
const climbSavePointTable = <(String, String, double, double, double, double, double)>[
  ('C1', 'tent', 0.86220, 0.74750, 0.09250, 0.03800, 0.90),
  ('C2', 'cabin', 0.19360, 0.54380, 0.07970, 0.03350, 1.00),
  ('C3', 'fountain', 0.76580, 0.44000, 0.05760, 0.02690, 1.00),
  ('C4', 'campfire', 0.31730, 0.33710, 0.06120, 0.02520, 0.90),
];

const climbSavePointBaseDrop = 0.25;

/// The flag (the summit_flag asset): the month's goal, on its own clearing,
/// in the same fields as [climbSavePointTable]; it lights only on the
/// month's last step.
const climbFlag = ('C6', 'summit_flag', 0.43080, 0.20530, 0.05340, 0.01730, 1.00);

/// The flag's pennant's median luminance (Rec. 709 on sRGB, 0–1): a theme
/// that recolours it (G10) scales its colour by each pixel's luminance over this.
const climbPennantLuminance = 0.5645;

/// Each object asset's height ÷ width (assets/climb/objects/).
const climbObjectAspects = <String, double>{
  'campfire': 0.94271,
  'tent': 0.81250,
  'fountain': 0.82292,
  'cabin': 0.74479,
  'summit_flag': 1.29688,
};

/// Dark mode (G6): per-channel gain, dark ÷ light, of the clearings' ground
/// in the theme's two backgrounds, by theme id.
const climbObjectDarkGain = <String, (double, double, double)>{
  'green_slope': (0.4824, 0.5182, 0.6714),
  'ember_peak': (0.6191, 0.7260, 0.9518),
  'glacier_peak': (0.5369, 0.5300, 0.6437),
  'red_canyon': (0.5989, 0.6145, 0.8091),
};
