/**
 * The pure part of the fallback-pool export (docs/1.1.0-shared-daily-test.md
 * §5; owner decision 2026-09-30): turns shared sets the live cron published
 * into the app's bundled pool asset (`assets/daily_test_fallback/pool.json`)
 * and a review file for the owner.
 *
 * Every set goes through the proxy's own gate (`validateSharedSet` with the
 * date's `dailyPlan`, imported from `proxy/src/shared_daily_test.ts`, so the
 * rules cannot drift), and must be prompt v2. Only the questions are kept:
 * `date`, `generatedAt`, `attempt` and `promptVersion` are dropped, and the
 * ids become `fbNN_i` (NN the set's place in the pool, i its question), so a
 * pool set's ids never look like a shared set's.
 *
 * Never imported by the Worker; bundled and run by `scripts/fallback_pool.sh`.
 */
import { dailyPlan, dayNumberOf, validateSharedSet, type SharedQuestion } from '../../proxy/src/shared_daily_test';

/** The asset format the app reads (`FallbackPool.formatVersion`). */
export const POOL_FORMAT_VERSION = 1;

/** The prompt version the pool accepts: the cron's live one (report §16). */
export const REQUIRED_PROMPT_VERSION = 2;

/** Sets in the pool (owner decision, report §13 answer 3). */
export const POOL_SIZE = 7;

export interface RawSet {
  /** The date asked for (the KV key `set:{date}`). */
  date: string;
  /** What `wrangler kv key get` printed. */
  text: string;
}

export interface PoolQuestion extends Omit<SharedQuestion, 'acceptedAnswers'> {}

export interface Pool {
  formatVersion: number;
  sets: { questions: PoolQuestion[] }[];
}

export interface ConvertResult {
  /** Present only when every set passed and the count is right. */
  pool?: Pool;
  /** One line per problem; empty when [pool] is present. */
  problems: string[];
  /** The owner's review file (Markdown); written only with [pool]. */
  review?: string;
}

/**
 * The JSON object in [text]: `wrangler` may print notices before it, so the
 * object starts at the first `{`.
 */
export function parseKvOutput(text: string): unknown {
  const start = text.indexOf('{');
  if (start < 0) throw new Error('no JSON object in the output');
  return JSON.parse(text.slice(start));
}

export function convert(raws: readonly RawSet[], expectedCount = POOL_SIZE): ConvertResult {
  const problems: string[] = [];
  const kept: { date: string; attempt: unknown; questions: SharedQuestion[] }[] = [];

  if (raws.length !== expectedCount) {
    problems.push(`expected ${expectedCount} dates, got ${raws.length}`);
  }
  const dates = new Set<string>();
  for (const raw of raws) {
    if (dates.has(raw.date)) {
      problems.push(`${raw.date}: listed twice`);
      continue;
    }
    dates.add(raw.date);
    if (dayNumberOf(raw.date) === null) {
      problems.push(`${raw.date}: not a YYYY-MM-DD date`);
      continue;
    }
    let set: Record<string, unknown>;
    try {
      const parsed = parseKvOutput(raw.text);
      if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) throw new Error('not an object');
      set = parsed as Record<string, unknown>;
    } catch (e) {
      problems.push(`${raw.date}: unreadable (${(e as Error).message}); is the set published?`);
      continue;
    }
    if (set.date !== raw.date) {
      problems.push(`${raw.date}: the stored set says date ${JSON.stringify(set.date)}`);
      continue;
    }
    if (set.promptVersion !== REQUIRED_PROMPT_VERSION) {
      problems.push(`${raw.date}: promptVersion ${JSON.stringify(set.promptVersion)}, needs ${REQUIRED_PROMPT_VERSION}`);
      continue;
    }
    const result = validateSharedSet(set, dailyPlan(raw.date));
    if (!result.ok) {
      problems.push(`${raw.date}: rejected by the proxy gate (${result.reason})`);
      continue;
    }
    kept.push({ date: raw.date, attempt: set.attempt, questions: result.questions });
  }
  if (problems.length > 0) return { problems };

  const sets = kept.map((set, n) => ({
    questions: set.questions.map((q, i): PoolQuestion => {
      const { acceptedAnswers: _dropped, ...rest } = q;
      return { ...rest, id: `${poolPrefix(n)}_${i + 1}` };
    }),
  }));
  return {
    pool: { formatVersion: POOL_FORMAT_VERSION, sets },
    problems: [],
    review: reviewMarkdown(kept.map((k, n) => ({ date: k.date, questions: sets[n]!.questions }))),
  };
}

export function poolPrefix(index: number): string {
  return `fb${String(index + 1).padStart(2, '0')}`;
}

/** Question texts and answers only, one section per set. */
export function reviewMarkdown(sets: readonly { date: string; questions: readonly PoolQuestion[] }[]): string {
  const lines = [
    '# Daily Test fallback pool — owner review',
    '',
    'Live-generated sets (prompt v2, `claude-sonnet-5-5` at `low` effort), each passed the proxy gate again at export.',
    'Question text and answers only. Regenerated by `scripts/fallback_pool.sh build`; do not edit by hand.',
    '',
  ];
  sets.forEach((set, n) => {
    lines.push(`## ${poolPrefix(n)} — published for ${set.date}`, '');
    set.questions.forEach((q, i) => {
      lines.push(`${i + 1}. \`${q.type}\` · ${q.topicId}`);
      if (q.context !== undefined) lines.push(`   - Context: ${q.context}`);
      lines.push(`   - Instruction: ${q.instruction}`);
      if (q.hint !== undefined) lines.push(`   - Hint: ${q.hint}`);
      lines.push(`   - **Answer:** ${q.correctAnswer}`);
      lines.push(`   - Predicted wrong: ${q.commonWrongAnswers.map((w) => w.answer).join(' · ')}`);
    });
    lines.push('');
  });
  return lines.join('\n');
}
